# Generated by Django 5.0.4 on 2024-04-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
