# Generated by Django 5.0.4 on 2024-04-28 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='files',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='products.product'),
            preserve_default=False,
        ),
    ]
