# Generated by Django 5.0.4 on 2024-04-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('phone', 'Phone'), ('telegram', 'Telegram'), ('mail', 'Mail'), ('address', 'Address')], max_length=100)),
                ('contact', models.CharField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('telegram', 'Telegram')], max_length=100)),
                ('contact', models.CharField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
